name: Deploy

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  ci-checks:
    name: CI Checks
    uses: ./.github/workflows/ci.yaml

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs:
      - ci-checks

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/dlbarduzzi/sentinel-api:latest
            ghcr.io/dlbarduzzi/sentinel-api:${{ github.sha }}
